version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbquery-v7
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    restart: unless-stopped
